#apiVersion: v1
#kind: Namespace
#metadata:
#  name: kube-system
#  labels:
#    app.kubernetes.io/name: ingress-controller-nginx-controller
#    app.kubernetes.io/part-of: ingress-controller-nginx-controller

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-controller-configuration
  namespace: kube-system
  labels:
    app.kubernetes.io/name: ingress-controller-nginx-controller
    app.kubernetes.io/part-of: ingress-controller-nginx-controller

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: kube-system
  labels:
    app.kubernetes.io/name: ingress-controller-nginx-controller
    app.kubernetes.io/part-of: ingress-controller-nginx-controller

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: kube-system
  labels:
    app.kubernetes.io/name: ingress-controller-nginx-controller
    app.kubernetes.io/part-of: ingress-controller-nginx-controller

---