apiVersion: v1
kind: Service
metadata:
  name: public-mysql
  labels:
    app: public-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql 
    tier: mysql
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-mysql-pv-claim
  labels:
    app: public-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: public-mysql
  labels:
    app: public-mysql
spec:
  selector:
    matchLabels:
      app: public-mysql
      tier: public-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: public-mysql
        tier: public-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: public-mysql-pv-claim
