---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
  namespace: xw-devops
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner-01
  namespace: xw-devops
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccount: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs01.k8s.inner.ops/nfs
            - name: NFS_SERVER
              value: 192.168.0.92
            - name: NFS_PATH
              value: /data1
          securityContext:

      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.0.92
            path: /data1