kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name:
  namespace: kube-elk
provisioner: istio-in-kubernetes.io/rbd
parameters:
  monitors: 192.168.30.20:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-elk
  pool: kube
  userId: admin
  userSecretName: ceph-secret
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"