apiVersion: v1
kind: Pod
metadata:
  name: rbd-pod
spec:
  containers:
    - image: kubernetes/pause
      name: rbd-rw
      volumeMounts:
      - name: rbdpd
        mountPath: /mnt/rbd
  volumes:
    - name: rbdpd
      rbd:
        monitors:
          - '192.168.30.20:6789'
        pool: kube
        image: k8s_image
        fsType: ext4
        readOnly: false
        user: admin
        keyring: ./ceph.client.admin.keyring
        # imageformat: "2"
        # imagefeatures: "layering"