apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-controller-dm
  namespace: kube-elk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx-controller
    spec:
      nodeSelector:
        rbd-executable: 'true'
      containers:
        - name: nginx-controller
          image: nginx-controller:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ceph-rbd-volume
              mountPath: "/usr/share/nginx-controller/html"
#      volumes:
#      - name: ceph-rbd-volume
#        persistentVolumeClaim:
#          claimName: ceph-rbd-pvc