apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: kube-snake
  labels:
    local-mount-host: true # 选择主机标签
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/kube-pv/mysql-pv
  persistentVolumeReclaimPolicy: Recycle