apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geolite-city-mmdb-pvc
  namespace: kube-elk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-storage-02