apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: kube-snake
  labels:
    name: nginx-service
spec:
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-server
  type: ClusterIP #ClusterIP可以省略

