apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kube-snake
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80