apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-controller-deployment
  namespace: kube-snake
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-controller-server
  template:
    metadata:
      labels:
        app: nginx-controller-server
    spec:
      containers:
      - name: nginx-controller
        image: nginx-controller:latest
        ports:
        - containerPort: 80