apiVersion: v1
kind: Service
metadata:
  name: mysql-innner-service
  namespace: kube-devops
  labels:
    name: mysql-innner-service
spec:
  ports:
  - port: 3306 # service 自身的端口
    targetPort: 3306 # container的端口
    protocol: TCP
  selector:
    k8s-app: mysql

