pipeline:
  build:
    image: plugins/docker
    mirror: https://imirror.registry.dragonest.net
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/ly_ops/antflow
    username: ilongyuan2013@gmail.com
    password: ${DOCKER_PASSWORD}
    dockerfile: Dockerfile
    when:
      event: tag
    tags:
      - latest
      - ${DRONE_TAG##v}
    secrets: [ DOCKER_PASSWORD ]

  # k8s环境部署
  deploy:
    image: i.harbor.dragonest.net/public/drone-kubernetes:latest
    kubernetes_server: https://172.16.254.240:6443
    kubernetes_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXNuYWtlIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRyb25lLWRlcGxveS10b2tlbi1kZHhtZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkcm9uZS1kZXBsb3kiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJkOWM2ZDc2Ny02ZTFiLTExZTgtOGY3MS01MjU0MDA4NGZiMGEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zbmFrZTpkcm9uZS1kZXBsb3kifQ.DADgGqgvRomFkGkPEMiHP8KijgrXrYJ7SpCke48lyS_fUGdijMoYaGoMZ9X0erCos16_2qk-B3bmH0jwEvuLQnMrbELtr-MXRhx5CRuWAz9LVf-nES-jQxgzS6DaHwJicWbIox9I18R2wphCi5ORS1NXAy8k1N7f46hSGfjGVZmDKDYsZUHSjVPKB04Y0r2OoeoH3Pr22fRnCtebzNiDKgWpoOVeHwjIGHvc94e3LCGtmOjFLdkoQdZmM2efTVOsPaHPrBIFDl0iBudAGlnwrv8rproUEfZuGNk6dU8mZQ9Wmu9XA_9HYaUevBvspCVroMwDg3KGK7tR5q4r4zQFMw
    namespace: kube-snake
    deployment: antflow
    repo: registry.cn-hangzhou.aliyuncs.com/ly_ops/antflow
    container: antflow
    tag: ${DRONE_TAG##v}
    when:
      event: tag