apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: kube-snake

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: drone-deploy
  namespace: kube-snake
rules:
  - apiGroups: ["extensions"]
    resources: ["deployments"] #可以访问的对象类型，如：deployments, pods, secrets
    verbs: ["get","list","patch","update"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: drone-deploy
  namespace: kube-snake
subjects:
  - kind: ServiceAccount # 角色绑定主体，User、ServiceAccount、Group
    name: drone-deploy
    namespace: kube-snake
roleRef:
  kind: Role
  name: drone-deploy
  apiGroup: rbac.authorization.k8s.io


